"""
Hidden Gems - Premium secret destinations most tourists don't know about
Off-the-beaten-path places, local favorites, and undiscovered wonders
Now with category-specific detail fields (difficulty, terrain, best_season, etc.)
"""

HIDDEN_GEMS = [
    # ========== EUROPE ==========
    {"name": "Civita di Bagnoregio", "description": "Hidden Gem - The 'dying city' perched on an eroding volcanic plateau in central Italy, connected by a single footbridge.", "category": "gem", "country": "Italy", "country_code": "IT", "latitude": 42.6275, "longitude": 12.1136, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit at sunrise for misty photos", "Only 10 permanent residents left"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - October", "crowd_level": "low", "terrain": "Volcanic plateau"},
    {"name": "Piran", "description": "Hidden Gem - A charming Venetian coastal town in Slovenia that most tourists skip for Dubrovnik.", "category": "gem", "country": "Slovenia", "country_code": "SI", "latitude": 45.5283, "longitude": 13.5681, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Climb the bell tower for panoramic views", "Try the local salt from Secovlje"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "May - September", "crowd_level": "low", "terrain": "Coastal town"},
    {"name": "Giethoorn", "description": "Hidden Gem - The 'Venice of the Netherlands' with no roads, only canals and footbridges between thatched-roof cottages.", "category": "gem", "country": "Netherlands", "country_code": "NL", "latitude": 52.7398, "longitude": 6.0758, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Rent a whisper boat to explore", "Visit in spring for flowers"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - September", "crowd_level": "medium", "terrain": "Canals / Wetland"},
    {"name": "Ronda", "description": "Hidden Gem - A dramatic clifftop city split by a 120m gorge in Andalusia, Spain, beloved by Hemingway.", "category": "gem", "country": "Spain", "country_code": "ES", "latitude": 36.7462, "longitude": -5.1612, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Walk the Puente Nuevo bridge at sunset", "Visit the oldest bullring in Spain"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "March - June", "crowd_level": "medium", "terrain": "Clifftop city"},
    {"name": "Sintra", "description": "Hidden Gem - A fairytale town near Lisbon with colorful Romanticist palaces hidden among forested hills.", "category": "gem", "country": "Portugal", "country_code": "PT", "latitude": 38.7873, "longitude": -9.3907, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit Pena Palace early morning", "Take the tram from Lisbon"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - June", "crowd_level": "medium", "terrain": "Forested hills"},
    {"name": "Kotor", "description": "Hidden Gem - A medieval fortified town on Montenegro's stunning Bay of Kotor, like a quieter Dubrovnik.", "category": "gem", "country": "Montenegro", "country_code": "ME", "latitude": 42.4247, "longitude": 18.7712, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Hike the fortress walls for bay views", "Visit before cruise ships arrive"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "May - September", "crowd_level": "medium", "terrain": "Coastal fjord"},
    {"name": "Ghent", "description": "Hidden Gem - A medieval Flemish city with more history per square meter than Brussels, without the crowds.", "category": "gem", "country": "Belgium", "country_code": "BE", "latitude": 51.0543, "longitude": 3.7174, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["See the Ghent Altarpiece painting", "Wander the Graslei waterfront"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - October", "crowd_level": "low", "terrain": "Canal city"},
    {"name": "Colmar", "description": "Hidden Gem - A perfectly preserved half-timbered village in Alsace that inspired Disney's Beauty and the Beast.", "category": "gem", "country": "France", "country_code": "FR", "latitude": 48.0794, "longitude": 7.3558, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit Little Venice quarter", "Try local Riesling wines"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - December", "crowd_level": "medium", "terrain": "Village / Riverfront"},
    {"name": "Rothenburg ob der Tauber", "description": "Hidden Gem - Germany's best-preserved medieval walled town, like stepping into a fairy tale.", "category": "gem", "country": "Germany", "country_code": "DE", "latitude": 49.3769, "longitude": 10.1789, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Walk the town walls at sunset", "Visit the Christmas Museum"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "May - December", "crowd_level": "medium", "terrain": "Hilltop walled town"},
    {"name": "Faroe Islands", "description": "Hidden Gem - 18 remote islands between Iceland and Norway with dramatic sea cliffs and grass-roofed villages.", "category": "gem", "country": "Denmark", "country_code": "DK", "latitude": 61.8926, "longitude": -6.9118, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Hike to Mulafossur waterfall", "Visit between May-September"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "May - September", "crowd_level": "low", "terrain": "Sea cliffs / Volcanic islands"},
    {"name": "Albarracin", "description": "Hidden Gem - A rose-colored medieval village perched above a gorge, voted Spain's most beautiful town.", "category": "gem", "country": "Spain", "country_code": "ES", "latitude": 40.4086, "longitude": -1.4441, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Walk the ancient city walls", "Visit the cave paintings nearby"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "April - October", "crowd_level": "low", "terrain": "Gorge / Hilltop village"},
    {"name": "Sveti Stefan", "description": "Hidden Gem - A tiny fortified island village on Montenegro's coast, now an exclusive resort.", "category": "gem", "country": "Montenegro", "country_code": "ME", "latitude": 42.2572, "longitude": 18.8933, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["View from the nearby public beach", "Sunset photos are spectacular"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "May - October", "crowd_level": "low", "terrain": "Coastal island"},

    # ========== ASIA ==========
    {"name": "Jiufen", "description": "Hidden Gem - A hillside gold mining town in Taiwan that inspired Spirited Away, with lantern-lit alleyways.", "category": "gem", "country": "Taiwan", "country_code": "TW", "latitude": 25.1094, "longitude": 121.8447, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit at dusk for lantern glow", "Try taro balls at the tea houses"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "September - November", "crowd_level": "medium", "terrain": "Hillside town"},
    {"name": "Bohol Chocolate Hills", "description": "Hidden Gem - Over 1,200 perfectly cone-shaped hills in the Philippines that turn chocolate-brown in dry season.", "category": "gem", "country": "Philippines", "country_code": "PH", "latitude": 9.8078, "longitude": 124.1030, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit Carmen viewpoint", "See the tarsier primates nearby"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "February - May", "crowd_level": "low", "terrain": "Limestone hills"},
    {"name": "Hoi An Ancient Town", "description": "Hidden Gem - A beautifully preserved Vietnamese trading port with lantern-lit streets and custom tailors.", "category": "gem", "country": "Vietnam", "country_code": "VN", "latitude": 15.8801, "longitude": 108.3380, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit during Lantern Festival (14th lunar day)", "Get custom clothing made overnight"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "February - May", "crowd_level": "medium", "terrain": "Riverside town"},
    {"name": "Hampi", "description": "Hidden Gem - Surreal boulder-strewn ruins of a once-great Indian empire scattered across an alien landscape.", "category": "gem", "country": "India", "country_code": "IN", "latitude": 15.3350, "longitude": 76.4600, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Rent a bicycle to explore", "Watch sunset from Matanga Hill"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "October - March", "crowd_level": "low", "terrain": "Boulder landscape / Ruins", "era": "Vijayanagara Empire (14th-16th Century)"},
    {"name": "Luang Prabang", "description": "Hidden Gem - A serene Laotian town where saffron-robed monks collect alms at dawn along the Mekong.", "category": "gem", "country": "Laos", "country_code": "LA", "latitude": 19.8856, "longitude": 102.1347, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Wake early for the monks' alms ceremony", "Climb Mount Phousi at sunset"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "November - March", "crowd_level": "low", "terrain": "Riverside / Mountain"},
    {"name": "Raja Ampat", "description": "Hidden Gem - Indonesia's remote island paradise with the highest marine biodiversity on Earth.", "category": "gem", "country": "Indonesia", "country_code": "ID", "latitude": -0.2334, "longitude": 130.5167, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Bring snorkeling gear everywhere", "Stay in a local homestay"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "October - April", "crowd_level": "low", "terrain": "Tropical islands / Coral reefs", "water_quality": "excellent"},
    {"name": "Yakushima Island", "description": "Hidden Gem - An ancient cedar forest island in Japan that inspired Princess Mononoke, shrouded in moss.", "category": "gem", "country": "Japan", "country_code": "JP", "latitude": 30.3486, "longitude": 130.5060, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Hike to the 7,000-year-old Jomon Sugi cedar", "Bring rain gear, it rains 35 days a month"], "is_premium": True, "is_unesco": False, "difficulty": "hard", "best_season": "May - July", "crowd_level": "low", "terrain": "Ancient cedar forest / Mountain"},

    # ========== AMERICAS ==========
    {"name": "Huacachina", "description": "Hidden Gem - A tiny desert oasis village built around a natural lagoon amid massive sand dunes in Peru.", "category": "gem", "country": "Peru", "country_code": "PE", "latitude": -14.0875, "longitude": -75.7626, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Go sandboarding at sunset", "Take a dune buggy tour"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "May - September", "crowd_level": "low", "terrain": "Desert oasis / Sand dunes"},
    {"name": "Valparaiso", "description": "Hidden Gem - Chile's bohemian port city with colorful hillside houses, street art, and funicular elevators.", "category": "gem", "country": "Chile", "country_code": "CL", "latitude": -33.0472, "longitude": -71.6127, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Walk the street art in Cerro Alegre", "Ride the historic ascensores"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "October - March", "crowd_level": "medium", "terrain": "Hillside coastal city"},
    {"name": "Guatape", "description": "Hidden Gem - A colorful Colombian town with a massive 700-step rock (La Piedra) overlooking a lake labyrinth.", "category": "gem", "country": "Colombia", "country_code": "CO", "latitude": 6.2337, "longitude": -75.1576, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Climb La Piedra del Penol for views", "Explore the colorful zocalos"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "December - March", "crowd_level": "medium", "terrain": "Lakeside / Granite monolith"},
    {"name": "Tulum Ruins", "description": "Hidden Gem - Ancient Mayan clifftop ruins overlooking the Caribbean Sea, one of the most scenic sites in Mexico.", "category": "gem", "country": "Mexico", "country_code": "MX", "latitude": 20.2145, "longitude": -87.4292, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Arrive at 8am opening for few crowds", "Swim in the cenote below the cliffs"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "November - April", "crowd_level": "high", "terrain": "Clifftop ruins / Beach", "era": "Maya Post-Classic (1200-1521 AD)"},
    {"name": "Salar de Uyuni Mirror", "description": "Hidden Gem - During wet season, the world's largest salt flat becomes a perfect mirror reflecting the sky.", "category": "gem", "country": "Bolivia", "country_code": "BO", "latitude": -20.1338, "longitude": -67.4891, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit Dec-April for mirror effect", "Stay for stargazing at night"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "December - April", "crowd_level": "low", "terrain": "Salt flat / High altitude desert"},

    # ========== AFRICA & MIDDLE EAST ==========
    {"name": "Chefchaouen", "description": "Hidden Gem - Morocco's blue city nestled in the Rif Mountains, every building painted in shades of blue.", "category": "gem", "country": "Morocco", "country_code": "MA", "latitude": 35.1688, "longitude": -5.2636, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Explore the blue medina on foot", "Hike to the Spanish Mosque viewpoint"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "March - May", "crowd_level": "medium", "terrain": "Mountain medina"},
    {"name": "Lalibela", "description": "Hidden Gem - Ethiopia's 'New Jerusalem' with 11 medieval rock-hewn churches carved from solid volcanic rock.", "category": "gem", "country": "Ethiopia", "country_code": "ET", "latitude": 12.0319, "longitude": 39.0437, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Visit during Timkat festival in January", "See the cross-shaped Church of St. George"], "is_premium": True, "is_unesco": False, "difficulty": "moderate", "best_season": "October - March", "crowd_level": "low", "terrain": "Highland plateau / Rock-hewn", "era": "12th-13th Century"},
    {"name": "Stone Town (Zanzibar)", "description": "Hidden Gem - A labyrinth of narrow alleys, ornate doors, and spice markets on the coast of Tanzania.", "category": "gem", "country": "Tanzania", "country_code": "TZ", "latitude": -6.1622, "longitude": 39.1921, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Take a spice tour", "Watch sunset from Forodhani Gardens"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "June - October", "crowd_level": "medium", "terrain": "Coastal town / Island"},
    {"name": "Socotra Island", "description": "Hidden Gem - Yemen's alien-looking island with dragon's blood trees found nowhere else on Earth.", "category": "gem", "country": "Yemen", "country_code": "YE", "latitude": 12.4634, "longitude": 53.8237, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Extremely remote, plan carefully", "Best visited Nov-March"], "is_premium": True, "is_unesco": False, "difficulty": "hard", "best_season": "November - March", "crowd_level": "low", "terrain": "Remote island / Unique flora"},

    # ========== OCEANIA ==========
    {"name": "Waitomo Glowworm Caves", "description": "Hidden Gem - New Zealand's underground caves lit by thousands of bioluminescent glowworms.", "category": "gem", "country": "New Zealand", "country_code": "NZ", "latitude": -38.2607, "longitude": 175.1060, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Take the boat ride through the glowworm grotto", "Black water rafting for adventurers"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "Year-round", "crowd_level": "medium", "terrain": "Limestone caves"},
    {"name": "Hobbiton", "description": "Hidden Gem - The real Shire movie set from Lord of the Rings, preserved in rolling New Zealand hills.", "category": "gem", "country": "New Zealand", "country_code": "NZ", "latitude": -37.8722, "longitude": 175.6830, "image_url": "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800", "tips": ["Book the evening banquet tour", "Visit in spring for blooming gardens"], "is_premium": True, "is_unesco": False, "difficulty": "easy", "best_season": "September - November", "crowd_level": "medium", "terrain": "Rolling green hills"},
]
