"""
Blue Flag Beaches worldwide - Premium content for subscribers
Comprehensive list of famous Blue Flag certified beaches with coordinates
Now with category-specific detail fields (water_quality, facilities, etc.)
"""

BLUE_FLAG_BEACHES = [
    # ========== SPAIN (Top Blue Flag country) ==========
    {"name": "Playa de La Concha", "description": "Blue Flag Beach - One of Europe's most famous urban beaches in San Sebastian, with a perfect shell-shaped bay and crystal-clear waters.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 43.3183, "longitude": -1.9857, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Best visited May-September", "Walk to Monte Urgull for views"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - September", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Accessibility ramps"]},
    {"name": "Playa de Rodas", "description": "Blue Flag Beach - Located on Cíes Islands, voted the world's best beach by The Guardian. Pristine white sand lagoon.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 42.2285, "longitude": -8.9017, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Ferry from Vigo required", "Daily visitor limit, book ahead"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "low", "facilities": ["Lifeguard", "Restrooms"]},
    {"name": "Playa de Muro", "description": "Blue Flag Beach - A stunning 6km stretch of fine white sand and shallow turquoise waters in Mallorca.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 39.7975, "longitude": 3.1150, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Shallow water perfect for families", "Visit the Albufera wetlands nearby"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Parking", "Beach bars"]},
    {"name": "Las Canteras Beach", "description": "Blue Flag Beach - Gran Canaria's premier urban beach with a natural reef creating a calm lagoon.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 28.1365, "longitude": -15.4370, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Great for snorkeling near La Barra reef", "Year-round swimming"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "Year-round", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Restrooms", "Accessibility ramps", "Parking"]},
    {"name": "Playa de Ses Illetes", "description": "Blue Flag Beach - Formentera's most famous beach with Caribbean-like turquoise waters and white sand.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 38.7252, "longitude": 1.4489, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Take a ferry from Ibiza", "Arrive early for best spot"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "high", "facilities": ["Beach bars", "Water sports rentals"]},
    {"name": "Playa de Bolonia", "description": "Blue Flag Beach - A wild and unspoiled beach near Tarifa with ancient Roman ruins of Baelo Claudia nearby.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 36.0884, "longitude": -5.7746, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit the Roman ruins", "Famous for its large sand dune"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Parking", "Restrooms"]},
    {"name": "Playa de la Malvarrosa", "description": "Blue Flag Beach - Valencia's main beach with wide golden sands and excellent seafood paella restaurants.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 39.4787, "longitude": -0.3264, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Try authentic paella nearby", "Connected to Las Arenas beach"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "May - October", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Beach volleyball", "Accessibility ramps"]},
    {"name": "Cala Macarella", "description": "Blue Flag Beach - A breathtaking cove in Menorca framed by limestone cliffs and pine forests.", "category": "beach", "country": "Spain", "country_code": "ES", "latitude": 39.9363, "longitude": 3.9384, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Walk to Macarelleta for a quieter cove", "Bring snorkeling gear"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Restrooms"]},

    # ========== GREECE ==========
    {"name": "Elafonissi Beach", "description": "Blue Flag Beach - Famous for its pink-tinged sand and shallow turquoise lagoon on Crete's southwest coast.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 35.2723, "longitude": 23.5417, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit early morning to avoid crowds", "Wade to Elafonissi islet"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "high", "facilities": ["Parking", "Restrooms", "Beach umbrellas"]},
    {"name": "Navagio Beach (Shipwreck)", "description": "Blue Flag Beach - Iconic beach on Zakynthos accessible only by boat, with a rusted shipwreck on white sand.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 37.8592, "longitude": 20.6246, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["View from the cliff viewpoint above", "Boat tours from Porto Vromi"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "high", "facilities": ["Boat access only"]},
    {"name": "Myrtos Beach", "description": "Blue Flag Beach - Kefalonia's most photographed beach with dramatic white cliffs and vivid blue water.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 38.3417, "longitude": 20.5258, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Best viewed from the road above", "Pebble beach - bring water shoes"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Parking", "Beach umbrellas"]},
    {"name": "Balos Lagoon", "description": "Blue Flag Beach - A stunning lagoon with sand bars and shallow warm water on Crete's northwest tip.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 35.5796, "longitude": 23.5878, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Take a boat from Kissamos", "Or hike down from the parking area"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "medium", "facilities": ["Boat tours", "Parking"]},
    {"name": "Red Beach (Santorini)", "description": "Blue Flag Beach - Unique beach at the base of dramatic red volcanic cliffs in Santorini.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 36.3492, "longitude": 25.3944, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Short walk from Akrotiri ruins", "Wear sturdy shoes on the path"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "May - October", "crowd_level": "high", "facilities": ["Beach umbrellas"]},
    {"name": "Sarakiniko Beach (Milos)", "description": "Blue Flag Beach - Lunar-like white volcanic rock formations meeting deep blue Aegean waters.", "category": "beach", "country": "Greece", "country_code": "GR", "latitude": 36.7479, "longitude": 24.4089, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Arrive before 10am for photos", "Cliff jumping is popular here"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Natural setting, minimal facilities"]},

    # ========== TURKEY ==========
    {"name": "Kaputas Beach", "description": "Blue Flag Beach - A stunning narrow beach between two cliffs near Kas with vivid turquoise water.", "category": "beach", "country": "Turkey", "country_code": "TR", "latitude": 36.2379, "longitude": 29.6493, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["187 steps down to the beach", "Less crowded in early morning"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "medium", "facilities": ["Parking", "Beach umbrellas"]},
    {"name": "Patara Beach", "description": "Blue Flag Beach - Turkey's longest beach at 18km with ancient Lycian ruins and protected sea turtle nesting.", "category": "beach", "country": "Turkey", "country_code": "TR", "latitude": 36.2712, "longitude": 29.3135, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit the ancient city of Patara", "Beach closes at sunset for turtles"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "low", "facilities": ["Lifeguard", "Parking", "Restrooms"]},
    {"name": "Oludeniz Blue Lagoon", "description": "Blue Flag Beach - One of Turkey's most photographed beaches where the Aegean meets a perfect blue lagoon.", "category": "beach", "country": "Turkey", "country_code": "TR", "latitude": 36.5488, "longitude": 29.1142, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Try paragliding from Babadag Mountain", "Lagoon has entrance fee"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Water sports", "Parking"]},
    {"name": "Lara Beach", "description": "Blue Flag Beach - Antalya's premium resort beach with golden sand stretching for kilometers.", "category": "beach", "country": "Turkey", "country_code": "TR", "latitude": 36.8530, "longitude": 30.7889, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit Duden Waterfalls nearby", "Beach clubs offer full service"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "May - October", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Beach clubs", "Parking"]},
    {"name": "Iztuzu Beach (Turtle Beach)", "description": "Blue Flag Beach - A unique sand spit between the Aegean and Dalyan River, home to loggerhead sea turtles.", "category": "beach", "country": "Turkey", "country_code": "TR", "latitude": 36.7806, "longitude": 28.5981, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Take a river boat from Dalyan", "No umbrellas allowed in turtle zone"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "low", "facilities": ["Restrooms", "Boat access"]},

    # ========== ITALY ==========
    {"name": "Spiaggia dei Conigli (Rabbit Beach)", "description": "Blue Flag Beach - Lampedusa's pristine cove repeatedly voted among the world's best beaches.", "category": "beach", "country": "Italy", "country_code": "IT", "latitude": 35.5094, "longitude": 12.5530, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Sea turtle nesting site", "Limited daily access in summer"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Lifeguard", "Restrooms"]},
    {"name": "Cala Goloritzé", "description": "Blue Flag Beach - A spectacular beach in Sardinia's Gulf of Orosei accessible only by sea or hiking.", "category": "beach", "country": "Italy", "country_code": "IT", "latitude": 40.0667, "longitude": 9.6397, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Hike from Golgo plateau", "Or take a boat from Cala Gonone"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "low", "difficulty": "moderate", "facilities": ["Natural setting"]},
    {"name": "Spiaggia della Pelosa", "description": "Blue Flag Beach - Stintino's Caribbean-like beach in northwest Sardinia with shallow crystal waters.", "category": "beach", "country": "Italy", "country_code": "IT", "latitude": 40.9619, "longitude": 8.2064, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Limited access, book online", "Bring reef shoes for rocks"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Parking"]},
    {"name": "Marina di Pescoluse", "description": "Blue Flag Beach - Known as the 'Maldives of Salento' in Puglia with white sand and crystal water.", "category": "beach", "country": "Italy", "country_code": "IT", "latitude": 39.8507, "longitude": 18.3076, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit Lecce nearby", "Less crowded in September"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Beach bars", "Parking"]},

    # ========== PORTUGAL ==========
    {"name": "Praia da Marinha", "description": "Blue Flag Beach - Algarve's most iconic beach with spectacular limestone arches and crystal water.", "category": "beach", "country": "Portugal", "country_code": "PT", "latitude": 37.0893, "longitude": -8.4114, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Hike the Seven Hanging Valleys trail", "Best photos from cliff top"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "medium", "facilities": ["Parking", "Restrooms"]},
    {"name": "Praia da Falésia", "description": "Blue Flag Beach - A 6km stretch of golden sand beneath dramatic red and orange sandstone cliffs.", "category": "beach", "country": "Portugal", "country_code": "PT", "latitude": 37.0839, "longitude": -8.1514, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Walk along the cliff tops at sunset", "Access via wooden stairways"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - October", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Parking"]},
    {"name": "Praia de Benagil", "description": "Blue Flag Beach - Famous for the nearby Benagil Cave, one of the world's most beautiful sea caves.", "category": "beach", "country": "Portugal", "country_code": "PT", "latitude": 37.0875, "longitude": -8.4266, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Kayak or swim to the cave", "Or take a boat tour"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "May - September", "crowd_level": "high", "facilities": ["Parking", "Boat tours"]},

    # ========== FRANCE ==========
    {"name": "Plage de Pampelonne", "description": "Blue Flag Beach - Saint-Tropez's legendary 5km beach on the French Riviera with celebrity beach clubs.", "category": "beach", "country": "France", "country_code": "FR", "latitude": 43.2279, "longitude": 6.6588, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Club 55 is the most iconic beach club", "Public sections available too"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Beach clubs", "Water sports", "Parking"]},
    {"name": "Plage de Palombaggia", "description": "Blue Flag Beach - Corsica's most beautiful beach with red rocks, pine trees, and turquoise water.", "category": "beach", "country": "France", "country_code": "FR", "latitude": 41.5614, "longitude": 9.2694, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit nearby Tamaricciu beach too", "Park early in summer"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "medium", "facilities": ["Parking", "Beach bars"]},
    {"name": "Plage de l'Espiguette", "description": "Blue Flag Beach - A wild, unspoiled 10km beach near Le Grau-du-Roi with sand dunes.", "category": "beach", "country": "France", "country_code": "FR", "latitude": 43.4900, "longitude": 4.1350, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Bring everything you need", "Protected natural area"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "June - September", "crowd_level": "low", "facilities": ["Parking"]},

    # ========== CROATIA ==========
    {"name": "Zlatni Rat (Golden Horn)", "description": "Blue Flag Beach - Croatia's most famous beach in Bol that changes shape with the wind and currents.", "category": "beach", "country": "Croatia", "country_code": "HR", "latitude": 43.2553, "longitude": 16.6339, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Excellent windsurfing spot", "View from Vidova Gora mountain"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Water sports", "Beach bars"]},
    {"name": "Bacvice Beach", "description": "Blue Flag Beach - Split's most popular city beach, famous for the traditional picigin ball game.", "category": "beach", "country": "Croatia", "country_code": "HR", "latitude": 43.5031, "longitude": 16.4467, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Try playing picigin", "Walk to Split Old Town nearby"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "June - September", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Beach bars"]},
    {"name": "Stiniva Beach", "description": "Blue Flag Beach - A hidden cove on Vis island, voted Europe's best beach, accessible by sea or cliff trail.", "category": "beach", "country": "Croatia", "country_code": "HR", "latitude": 43.0261, "longitude": 16.1592, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Steep 20-minute hike down", "Or take a boat from Vis"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - September", "crowd_level": "low", "difficulty": "moderate", "facilities": ["Natural setting"]},

    # ========== CARIBBEAN & AMERICAS ==========
    {"name": "Flamenco Beach", "description": "Blue Flag Beach - Puerto Rico's Culebra island gem, consistently ranked among the world's top beaches.", "category": "beach", "country": "Puerto Rico", "country_code": "PR", "latitude": 18.3281, "longitude": -65.3195, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Fly or ferry from mainland PR", "See the old tank on the beach"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "December - April", "crowd_level": "medium", "facilities": ["Restrooms", "Camping", "Parking"]},
    {"name": "Grace Bay Beach", "description": "Blue Flag Beach - Turks and Caicos' world-famous 12-mile stretch of powder-white sand.", "category": "beach", "country": "Turks and Caicos", "country_code": "TC", "latitude": 21.7964, "longitude": -72.1647, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Snorkel the reef offshore", "Sunset walks are magical"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "November - May", "crowd_level": "medium", "facilities": ["Water sports", "Beach bars", "Restrooms"]},
    {"name": "Eagle Beach", "description": "Blue Flag Beach - Aruba's widest beach with iconic fofoti trees and calm Caribbean waters.", "category": "beach", "country": "Aruba", "country_code": "AW", "latitude": 12.5567, "longitude": -70.0527, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Photograph the famous divi-divi trees", "Sea turtle nesting site"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "Year-round", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Restrooms", "Beach palapas"]},
    {"name": "Playa del Carmen", "description": "Blue Flag Beach - Mexico's Riviera Maya beach town with white sand and vibrant beach scene.", "category": "beach", "country": "Mexico", "country_code": "MX", "latitude": 20.6296, "longitude": -87.0739, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Walk the 5th Avenue for shopping", "Ferry to Cozumel for diving"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "December - April", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Beach clubs", "Water sports", "Restaurants"]},
    {"name": "Playa Delfines", "description": "Blue Flag Beach - Cancun's most beautiful public beach with the iconic Cancun sign.", "category": "beach", "country": "Mexico", "country_code": "MX", "latitude": 21.0807, "longitude": -86.7710, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Take photos with the Cancun sign", "Strong waves, be careful swimming"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "December - April", "crowd_level": "high", "facilities": ["Lifeguard", "Restrooms", "Parking"]},
    {"name": "Copacabana Beach", "description": "Blue Flag Beach - Rio de Janeiro's iconic crescent-shaped beach, one of the most famous in the world.", "category": "beach", "country": "Brazil", "country_code": "BR", "latitude": -22.9711, "longitude": -43.1826, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit on a weekday for fewer crowds", "Try an acai bowl at the kiosks"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "December - March", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Beach kiosks", "Sports facilities"]},

    # ========== ASIA & OCEANIA ==========
    {"name": "Radhanagar Beach", "description": "Blue Flag Beach - Havelock Island in India's Andamans, voted Asia's best beach multiple times.", "category": "beach", "country": "India", "country_code": "IN", "latitude": 11.9806, "longitude": 92.9497, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit for sunset", "No facilities, bring water"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "October - May", "crowd_level": "low", "facilities": ["Minimal facilities"]},
    {"name": "Kovalam Beach", "description": "Blue Flag Beach - Kerala's crescent-shaped lighthouse beach with Ayurvedic resorts and coconut palms.", "category": "beach", "country": "India", "country_code": "IN", "latitude": 8.3988, "longitude": 76.9782, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Climb the lighthouse for views", "Try Ayurvedic massage"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "October - March", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Restaurants"]},
    {"name": "Rushikonda Beach", "description": "Blue Flag Beach - Visakhapatnam's golden sand beach popular for water sports on India's east coast.", "category": "beach", "country": "India", "country_code": "IN", "latitude": 17.7826, "longitude": 83.3836, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Try jet skiing and surfing", "Visit the hilltop temple"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "October - March", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Water sports", "Parking"]},
    {"name": "Shirahama Beach", "description": "Blue Flag Beach - One of Japan's few Blue Flag beaches with stunning white sand in Wakayama Prefecture.", "category": "beach", "country": "Japan", "country_code": "JP", "latitude": 33.6774, "longitude": 135.3419, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit Engetsu Island nearby", "Hot spring hotels along the coast"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "July - August", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Parking"]},
    {"name": "Bondi Beach", "description": "Blue Flag Beach - Sydney's most iconic beach with world-class surf and the famous coastal walk.", "category": "beach", "country": "Australia", "country_code": "AU", "latitude": -33.8915, "longitude": 151.2767, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Walk the Bondi to Coogee trail", "Swim between the flags"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "December - February", "crowd_level": "high", "facilities": ["Lifeguard", "Showers", "Restrooms", "Parking", "Accessibility ramps"]},
    {"name": "Whitehaven Beach", "description": "Blue Flag Beach - Whitsundays' pristine 7km silica sand beach accessible only by boat or seaplane.", "category": "beach", "country": "Australia", "country_code": "AU", "latitude": -20.2826, "longitude": 149.0392, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Visit Hill Inlet lookout at high tide", "Day trip from Airlie Beach"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - October", "crowd_level": "low", "facilities": ["Boat access only", "Restrooms"]},

    # ========== AFRICA & MIDDLE EAST ==========
    {"name": "Camps Bay Beach", "description": "Blue Flag Beach - Cape Town's glamorous beach backed by the Twelve Apostles mountain range.", "category": "beach", "country": "South Africa", "country_code": "ZA", "latitude": -33.9506, "longitude": 18.3780, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Sundowners at a beachfront restaurant", "Cold Atlantic water!"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "December - March", "crowd_level": "high", "facilities": ["Lifeguard", "Restrooms", "Restaurants"]},
    {"name": "Clifton 4th Beach", "description": "Blue Flag Beach - Cape Town's most sheltered beach with crystal water and granite boulders.", "category": "beach", "country": "South Africa", "country_code": "ZA", "latitude": -33.9408, "longitude": 18.3732, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Steps down are steep", "Protected from the wind"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "December - March", "crowd_level": "medium", "facilities": ["Lifeguard"]},
    {"name": "Muizenberg Beach", "description": "Blue Flag Beach - Famous for its colorful Victorian bathing boxes and beginner-friendly surf.", "category": "beach", "country": "South Africa", "country_code": "ZA", "latitude": -34.1094, "longitude": 18.4717, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Take a surfing lesson", "Photo the iconic beach huts"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "December - March", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Surf rentals", "Parking"]},
    {"name": "Essaouira Beach", "description": "Blue Flag Beach - Morocco's windswept Atlantic beach, perfect for windsurfing and kitesurfing.", "category": "beach", "country": "Morocco", "country_code": "MA", "latitude": 31.5085, "longitude": -9.7595, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Try camel riding on the beach", "Explore the medina nearby"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "May - September", "crowd_level": "medium", "facilities": ["Water sports", "Restaurants"]},
    {"name": "Aqaba South Beach", "description": "Blue Flag Beach - Jordan's Red Sea beach with warm waters and incredible coral reef snorkeling.", "category": "beach", "country": "Jordan", "country_code": "JO", "latitude": 29.5146, "longitude": 35.0035, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Snorkel the Japanese Garden reef", "Combine with Wadi Rum trip"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "March - May", "crowd_level": "medium", "facilities": ["Lifeguard", "Showers", "Diving centers", "Restaurants"]},

    # ========== NORTHERN EUROPE ==========
    {"name": "West Wittering Beach", "description": "Blue Flag Beach - One of England's finest sandy beaches with views to the South Downs.", "category": "beach", "country": "United Kingdom", "country_code": "GB", "latitude": 50.7697, "longitude": -0.9033, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Book parking in advance", "Walk to East Head sand spit"], "is_premium": True, "is_unesco": False, "water_quality": "good", "best_season": "June - August", "crowd_level": "high", "facilities": ["Lifeguard", "Parking", "Restrooms"]},
    {"name": "Banna Strand", "description": "Blue Flag Beach - Kerry's spectacular 6-mile beach with dramatic views of the Slieve Mish mountains.", "category": "beach", "country": "Ireland", "country_code": "IE", "latitude": 52.2667, "longitude": -9.8500, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Great for horse riding", "Wild Atlantic Way stop"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - August", "crowd_level": "low", "facilities": ["Lifeguard", "Parking"]},
    {"name": "Keem Bay", "description": "Blue Flag Beach - A secluded beach on Achill Island with dramatic cliff surroundings.", "category": "beach", "country": "Ireland", "country_code": "IE", "latitude": 53.9696, "longitude": -10.1960, "image_url": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800", "tips": ["Drive the Atlantic Drive first", "Watch for basking sharks"], "is_premium": True, "is_unesco": False, "water_quality": "excellent", "best_season": "June - August", "crowd_level": "low", "facilities": ["Parking"]},
]
